default: &default
  # Telegram environment variables
  telegram_api_id: 'TELEGRAM_API_ID'
  telegram_api_hash: 'TELEGRAM_API_HASH'
  telegram_bot_token: Null
  wheel_userids:
    - 1698923450
  plugins:
    root: 'plugins.user_plugins'
    include: Null
    exclude: Null

clients: # session_name: {options}
  owo: {<<: *default}
#  kjb2k124vk2jv41214bj2k4b12kb12k4v2: {<<: *default} # session_name can be substituted for session string

# Notes:
#
# All plugin root directories should be in plugins directory

# Examples:
#
### Your own client sets ###
#custom: &custom
#  <<: *default # This line ensures non recursive inheritance from default client set
#  plugins:
#    root:
#      - 'plugins.extra_plugins'
#    include:
#      - 'extra_plugin'
#    exclude:
#      - 'unwanted'
#  wheel_userids:
#    - 12312421
#    - 25235423
#    - 21424111
#  ...
#
#sessions:
#  something: {<<: *custom}
### Your own client sets ###

### A single value to modify ###
#extra_plugins: &extra_plugins
#  root: 'extra_plugins'
#
#sessions:
#  something: {<<: *default, *extra_plugins}
# OR
#  something: {<<: *default, plugins: {root: 'extra_plugins'}}
### A single value to modify ###
